### PR TITLE
Quiz Home page and rules page

### PR DESCRIPTION
**Pull request by praveenreddy1798**
**Home page**

Screenshot 2022-02-17 at 4 56 11 AM

**Rules Page**

Screenshot 2022-02-17 at 4 56 37 AM

### CODE REVIEW

**Review by vaibhav18matere — APPROVED** [review]
looks good to me!
 you can re-think about the background color you have used! I would suggest to use lighter shades of color or some color-gradient combination.

**Comment by praveenreddy1798** [comment]
> looks good to me! you can re-think about the background color you have used! I would suggest to use lighter shades of color or some color-gradient combination.

Sure, will give a thought to it

**Review by rahulk31 — APPROVED** [review]
Really liked the way you have used your CL throughout. Could not find any flaw in the code though. One suggestion would be change images because of the png background look. LGTM 👍

**Comment by praveenreddy1798** [comment]
> Really liked the way you have used your CL throughout. Could not find any flaw in the code though. One suggestion would be change images because of the png background look. LGTM 👍

Screenshot 2022-02-17 at 11 58 29 PM

Making this change

**Pull request merged**
